### ISSUE TITLE
Few questions :)

### ISSUE THREAD

**Issue by marksev1** [ribico/gr-home-automation#12]
Hello ribico, this is Marko from Souliss groups.

I have a few questions which I would rather ask here then on the groups, don't worry I will close the issue as soon as I get the answers :).

For MQTT support with local broker (Mosquitto) are you going to use this library - https://github.com/knolleary/pubsubclient
Do you use Juan's esp code? If not would you help me port this mqtt thing there, since I'm a noob :(. Or maybe I'll wait for the future because Juan has it planned. I'd like to test it with Node-red.

That cloud-io gateway that you have, will it be the gateway for the entire house, or can you have 2 gateways one just for sending data to the cloud? And how do you do that?

Have a nice day Ribico!

**Comment by ribico** [comment]
Ciao marksev1,
yes I use that lib and should work with standard local MQTT server.
I would like help you but unfortunaley I have NO TIME due to work in the
office and at home and two young children.
If you prepare a sketch working with MQTT and your server without SOULISS I
can help you to integrate it with souliss.

the GW is my second GW.
You can have as many GW as you want in your network.

BR
- gabriele

2016-02-16 12:33 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Thanks, yeah totally understandable, of course family and work comes first. 

Should I just get the example working or does it need to be somehow applicable/specific to Juan's esp-sketch since I would like to have it there. 

In that case I would need to then ask you if Souliss packages some data into some variables which I could use to point to specific MQTT topic, for example one for temperature, one for some other sensor.

Or if its maybe possible to automate that process of putting stuff into MQTT topics.

Regarding setting up second gateway is there some special procedure or just set it as gateway and it will work. For example that cloud-one of yours is nice I might deploy that. But need to buy more esp's, 3 are not enough :)

**Comment by ribico** [comment]
I am sorry I have just little experience with MQTT
Please write your own MQTT sketch first just publishing the content of a
local variable.
Don't care about Souliss at the beginning, I will help you with the
integration then.

BR
- gabriele

2016-02-18 11:28 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Ribico, I have found some examples on github (for temperature sensors): 

https://github.com/sylvek/iot/blob/e14dbd7d001e8be0eee6db7fdf4d041f37a7f577/esp8266_thermometer_mqtt/esp8266_thermometer_mqtt.ino

https://github.com/sylvek/iot/blob/b77236bb5831ec0932f07f017209919d6401d4d6/esp8266_thermometer_low_consumption_mqtt/esp8266_thermometer_low_consumption_mqtt.ino

https://github.com/ajvuik/MQTT_Node_ESP8266/blob/c3c55ef06f014af6c43b180f521404a092af9be8/MQTT_Node_ESP8266.ino

https://github.com/boneskull/arduino-sketches/blob/d66419a3e1ae45b3cb88fc7f9bd3375336ef68eb/esp8266-thermostat/esp8266-thermostat.ino

I didn't yet tested them. But I plan to test them. I also tried to find HCSR501 examples but I couldn't find those. Can you maybe help me choose which one would be best to try and test? :)

**Comment by ribico** [comment]
The first is perfect.
try to flash an ESP with that one and come back when working.

ciao

2016-02-18 18:53 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Thanks! I will report when I do :)
Thanks for guidance ribico!

Got another question, maybe you are not the right one to answer, but on these Juan's-esp-Soulissdomo. When I arm antitheft I immediately get ALARM even though I'm not infront of PIR sensor. So now I don't know if its a bug of Juan's Soulissdomo or of Soulissapp.

Ciao

**Comment by ribico** [comment]
No idea, but please note that the Souliss Antitheft system gives you an alarm also when the boards in the network are not communicating for safety reasons.

**Comment by marksev1** [comment]
Is it ok if I have PIR on Gateway or should it be only on Peer? (maybe because of that?)

**Comment by marksev1** [comment]
Ribico just for informational purposes I tried this firmware ->
http://www.esp8266.nu/index.php/Main_Page and it worked fine with both
DS-temperature sensor and PIR sensor, of course with MQTT protocol... Hope
I'll be able to get the PIR sensor to work in Souliss also since I like
SoulissApp :) and I like the sensor auto-detect :).

2016-02-19 15:32 GMT+01:00 ribico notifications@github.com:
